### ISSUE TITLE
Nullpointer in Travis fixen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Integration#21]
Der Build auf Travis erzeugt eine Nullpointe-Exeption. siehe [https://travis-ci.org/hu-semesterprojekt-genombrowser/Alazen/builds/104847918]
Edit: Wenn ich das bei mir ausführe, bekomme ich:
```  
     [java] Data will be loaded anew.
     [java] Deleting old data...
     [java] Old data deleted!
     [java] Starting local parsers...
     [java] java.io.IOException: Cannot run program "psql": error=2, No such file or directory
     [java] Starting to copy meta data to the database...
     [java] Finished copying meta data to the database!
     [java] Starting to copy mutation data into the database...
     [java] Ihr habt mich gerufen. Hier bin ich!
     [java] Starting 1000 Genome Project Parser...
     [java] Connecting to FTP server
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
     [java] 	at main.main(main.java:46)
     [java] Caused by: java.io.IOException: error=2, No such file or directory
     [java] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
     [java] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
     [java] 	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
     [java] 	... 1 more
     [java] java.io.IOException: Cannot run program "psql": error=2, No such file or directory
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
     [java] 	at main.main(main.java:46)
     [java] Caused by: java.io.IOException: error=2, No such file or directory
     [java] 	at java.lang.UNIXProcess.forkAndExec(Native Method)
     [java] 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
     [java] 	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
     [java] 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
     [java] 	... 1 more
     [java] Exception in thread "Thread-0" java.lang.NullPointerException
     [java] 	at copyThread.copyMuta(copyThread.java:18)
     [java] 	at copyThread.run(copyThread.java:87)
     [java] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MasterOfDesaster** [comment]
Wo führst du das aus? Auf deinem eigenen Rechner?
Das Problem tritt bei den Kopiervorgängen in die DB auf, wenn ich das richtig sehe, wofür du postgreSQL brauchst mit entsprechender DB und Tabellen, auf der VM läuft es nachweisbar einwandfrei.

**Comment by BenSchumacher-HU** [comment]
Kannst du eine Abfrage darumbauen, ob postgreSQL läuft? Dann können wir diesen Fehler abfangen

**Comment by MasterOfDesaster** [comment]
Ist leider von Java aus nicht möglich. Es gibt zwar eine Terminaleingabe, bei der eine 1 returned wird, falls Postgres nicht installiert ist, aber ich finde keine Möglichkeit, dass dieser Wert an Java übergeben wird. Somit lässt sich das wohl leider nicht machen.
Müssen sich die Nutzer halt an das, jetzt endlich fertige, Readme halten ^^

**Comment by BenSchumacher-HU** [comment]
Danke für die Info, damit ist das dann erledigt
